### ISSUE TITLE
Reduce unnecessary XPATH evaluation

### ISSUE THREAD

**Issue by zealotrunner** [FluentDOM/FluentDOM#15]
@f433aa41
`find()` method always uses option `Nodes\Fetcher::UNIQUE`

I think `UNIQUE` is not necessary in many situations, but may cause large amount of calculation, uses too many CPU resources.

This simple `find` could lead to hundreds of XPATH evaluation.

     $html->find('table#content tr');

**Comment by ThomasWeinert** [comment]
I am preparing the 5.2 release at the moment. If you have other suggestion please comment.

**Comment by ThomasWeinert** [comment]
Optimized the calls to the compare: https://github.com/FluentDOM/FluentDOM/issues/23
