### ISSUE TITLE
FluentDOM 5.x 6x slower than 4.x ?

### ISSUE THREAD

**Issue by ddebin** [FluentDOM/FluentDOM#23]
Why is this piece of code 6x slower with FluentDOM 5.x compared to 4.x ? (HHVM or not)

```php
$fd = FluentDOM($html, 'text/html');
$r = array();
foreach ($fd->find("//tr[@class='product']") as $fd_child)
{
	$rr = array();
	$rr['imgsrc'] = $fd_child->find("td[@class='image']//img")->attr("src");
	$h3 = $fd_child->find("td[@class='specs']//h3");
	$rr['url'] = $h3->find("a")->attr("href");
	$rr['title'] = $h3->text();
	$rr['desc'] = $fd_child->find("td[@class='specs']")->xml();
	$rr['price'] = $fd_child->find("td[@class='purchase-info']//span[@itemprop='price']")->text();
	$rr['savings'] = $fd_child->find("td[@class='purchase-info']//p[@class='savings']")->text();
	$r[] = $rr;
}
```

**Comment by ThomasWeinert** [comment]
Which FluentDOM 5.x? I changed find() in 5 to match the jQuery behavior. But this had an impact on the performance. So I optimized it with 5.2 and added the other behavior as an option.

Have you tried it with 5.2?

**Comment by ddebin** [comment]
4.1.5 vs. 5.2.1 (same for 5.1.x)
Ubuntu 14.04
PHP 5.5.9 / CLI mode

**Comment by ThomasWeinert** [comment]
Version | Time
----------|--------
4.1 | 1.20
5.2 (no optimization) | 2.47
5.2 (1. opt: avoid sort) | 1.89
5.2 (Document) | 0.72

**Comment by ddebin** [comment]
Thanks for your help, I will work on a sample script (with an HTML file) to help you track the problem.

**Comment by ddebin** [comment]
@ThomasWeinert Here is the PHP sample script (http://pastebin.com/B4jMxWqQ) and HTML data (http://pastebin.com/FtDmzjjJ)

With FD 4.1.2 :

    # time php -f test_fd.php
    php -f test_fd.php  3.18s user 0.03s system 99% cpu 3.217 total

With FD 5.2.0 :

    # time php -f test_fd.php
    php -f test_fd.php  26.73s user 0.10s system 99% cpu 26.919 total

(Ubuntu 14.04, PHP 5.5.9)

**Comment by ddebin** [comment]
Besides this "performance" problem, FD (tested with the same script) is (memory) leaking A LOT with HHVM 3.5.0 ; but I think it's more on HHVM's side...

**Comment by ThomasWeinert** [comment]
Could you please test [https://github.com/FluentDOM/FluentDOM/commit/848a4ee18435b116f659b6e3a93ced18ab178182]?

**Comment by ddebin** [comment]
It's a lot better, but it's still 30% slower.

    php -f test_fd.php  4.05s user 0.12s system 99% cpu 4.173 total

vs.

    php -f test_fd.php  3.17s user 0.05s system 99% cpu 3.227 total

**Comment by ThomasWeinert** [comment]
I will keep looking into the xdebug profiling files, but for the moment I don't see something where I could optimize it. Here are new features in the background (namespace handling for example) - so here is some more code to be executed. 

*btw* Could you give me your numbers for this approach? https://gist.github.com/ThomasWeinert/11452b95d6f93376189f

**Comment by ddebin** [comment]
You approach is now **faster**...

    php -f test_fd.php  2.16s user 0.18s system 99% cpu 2.346 total

My job is now to understand what was wrong with my approach since yours is different in many ways.

Anyway, many thanks for your help :-)
I think you can close this issue.

**Comment by ThomasWeinert** [comment]
The document based approach uses mostly shortcuts. It basically works a lot more directly with the ext/dom and a lot less php userland function calls.

For example:

```php
$rr['imgsrc'] = $child("string(td[@class='image']//img/@src)");
```

Is in ext/dom
```php
$rr['imgsrc'] = $xpath->evaluate("string(td[@class='image']//img/@src)", $child);
```

I can not reproduce the memory leak. If I output the `memory_get_peak_usage(TRUE)`, it will increase with the calls (1MB for a single call, 3.1MB for 250 calls). But if I add `gc_collect_cycles()` to trigger the GC after each call it only increases to 1.3 MB with 2, 250 or 2500 calls.

**Comment by ddebin** [comment]
OK, thank you for the explanation.
I think you can close this issue.

**Comment by ThomasWeinert** [comment]
Added FluentDOM\Nodes::FIND_FORCE_SORT as an option for FluentDOM\Nodes::find() to disable the optimization.

Added a cache for QualifiedName validations (avoids multiple PCRE calls for the same tag name.)
