### ISSUE TITLE
Using html fragments instead of CssSelector wrapping source code in <html> tags

### ISSUE THREAD

**Issue by digra5319** [FluentDOM/FluentDOM#24]
When passing in fragments of html into FluentDOM::QueryCss() it will wrap it with <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html><body> ... </body></html>. Is it possible not to have the fragment wrapped?

**Comment by ThomasWeinert** [comment]
It is not really possible to avoid it. The DOMDocument will repair HTML if loaded. Adding the doctype it part of that. 

Three possible solutions:

1) Find and save the `html` element: 

```
echo FluentDOM::QueryCss($source, 'html')->find('html')->html();
```

2) Save the document element of the attached document.

```
$query = FluentDOM::QueryCss($source, 'html');
echo $query->document->documentElement->saveHtml();
```

3) Write a loader that copies the `html` element into a new document before returning it. 

I am not about it. It has a lot of implications, here are libxml options for it, but they are not always available. I am still thinking how to allow the use of them.

**Comment by digra5319** [comment]
Great, thank you for the help.
