### ISSUE TITLE
FluentDOM::load($html, 'text/html') crashes the browser

### ISSUE THREAD

**Issue by gordielachance** [FluentDOM/FluentDOM#29]
When running this code, the website crashes with error *ERR_EMPTY_RESPONSE*...

        $html='<a>hello</a>';
        require_once($this->plugin_dir . '_inc/php/autoload.php');
        $fd = FluentDOM::load($html, 'text/html');

The line

        $fd = FluentDOM::load($html, 'text/html');

Makes it crash..
Any idea ?

**Comment by ThomasWeinert** [comment]
Well it does not crash the browser, but the PHP script process on the server, resulting in a empty response. I can not really say why without an error message and more information.

A good place to look would be the log files of the server. If possible increase the error reporting level.

Have you tried to use it without Wordpress? A simple PHP script just with the lines for FluentDOM?

**Comment by gordielachance** [comment]
Here's a part of my code and the error which is fired : http://pastie.org/private/rkn87cosj7h9hkbnl1g

**Comment by ThomasWeinert** [comment]
`FluentDOM::load()` returns an instance of `FluentDOM\Document` an extended version of `DOMDocument`. It implements `find()`, But basically you call:

```php
$fd = FluentDOM::Query($html, 'text/html')->find('body');
```
This is `Query()` not `QueryCSS()`, so the result supports XPath expressions, not CSS selectors.
`body` is a valid XPath expression (the `body` child element nodes of the current context). But `.titre` is not a valid XPath expression. So it reports that it did not return a node list. I will look into improving the error message.

You can use FluentDOM::QueryCSS() and CSS selectors:

```php
$fd = FluentDOM::QueryCSS($html, 'text/html')->find('body')->find('.titre');
```
Or FluentDOM::Query() and XPath expressions:

```php
$fd = FluentDOM::Query($html, 'text/html')
  ->find('//body')
  ->find('.//*[contains(concat(" ", normalize-space(@class), " "), " titre ")]');
```

Here is a tool that can convert CSS selectors into XPath expressions: 
http://xpath.thomas.weinert.info/?selector=.titre
