### ISSUE TITLE
Carica/PhpCss VS Symfony/CssSelector

### ISSUE THREAD

**Issue by salarmehr** [FluentDOM/FluentDOM#31]
I do appreciate for this excellent package. May you please provide some info regarding choosing between Carica/PhpCss and Symfony/CssSelector in the docs?

**Comment by ThomasWeinert** [comment]
I don't know the current state of the Symfony package. Not sure if it makes any difference which package you use now. You can test the PHPCss converter at [http://xpath.thomas.weinert.info](http://xpath.thomas.weinert.info).
