### ISSUE TITLE
null parameter does not work as expected

### ISSUE THREAD

**Issue by salarmehr** [FluentDOM/FluentDOM#33]
When for example `$dom->text($text)` is invoked while `$text=null`, the method acts as a getter while it is intended to be a setter (following jQuery). This is also true for `attr('foo',null)` and others. Sending null and sending no parameter needs to be distinguished.  I think `public function html($html = NULL) {}` need to be converted to `public function html() {}` and the arguments fetched by `func_get_args` function.

**Comment by ThomasWeinert** [comment]
Why? If you need to remove the content you can send an empty string as value.

**Comment by salarmehr** [comment]
Why what? It about making it compatible with jQuery API. 
Consider the following example:

    $dom->html($w)->attr('placeholser',$x)->$attr('maxlength',$y)->$att('title',$t); 

If any of $w,$t, .. variables is null the corresponding method will acts as a getter, the chain will broken and an exception will be thrown. This is not the case in jQuery api.

**Comment by ThomasWeinert** [comment]
You can always cast the variables.
`$dom->html((string)$w)->attr('placeholder',(string)$x)...`

PHP functions usually make no difference between NULL and undefined. NULL is for optional parameters (type hints, but internal functions, too).

In your example you provide the arguments. See this [example](https://eval.in/540194):

```php
function dump() {
  var_dump(func_get_args());
}
dump($a, $b);
```
```
array(2) {
  [0]=>
  NULL
  [1]=>
  NULL
}
```

**Comment by salarmehr** [comment]
```
function attr()
{
//    return count(func_get_args());
    if (count(func_get_args()) == 1) {
        return 'I am a getter!';
    };
    return 'I am a setter!!';
}

echo attr('type').PHP_EOL;
echo attr('type',null).PHP_EOL;
echo attr('type','foo');
```

```
I am a getter!
I am a setter!!
I am a setter!!
```

**Comment by ThomasWeinert** [comment]
Yes, but even an undefined variable like in my example is treated as NULL. I will think about it, but I am a little afraid how much code (that uses FD) would break.

**Comment by salarmehr** [comment]
I don't know what you are trying to show by that example. May you please provide an example of breaking code?

**Comment by ThomasWeinert** [comment]
Some source that wraps or extends the current methods. It would expect the current behavior. If a method extends FluentDOM:attr() and calls the parent method expecting the current behavior it will break.

**Comment by ThomasWeinert** [comment]
Variadics allow for a cleaner implementation of optional arguments (then func_get_args()) and even for generic wrapper functions:

```php
function attr($name, ...$arguments) {
  var_dump($arguments);
}

function attributes($name, ...$arguments) {
  attr($name, ...$arguments);
}

attributes('one');
attributes('two', '21');
```

**Comment by salarmehr** [comment]
Well done. Thanks.
