### ISSUE TITLE
html treated as xml?

### ISSUE THREAD

**Issue by inquam** [FluentDOM/FluentDOM#40]
Back in the day I used phpQuery for altering rendered pages just before they are send to the client. Since that project has been quite silent for a long time I decided to look for something else when I needed the same functionality again. I found a few and FluentDOM was one of them. I tested it along with the two officially supported css selectors.

I decided to start by benchmarking the same functionality in FluentDOM and phpQuery and was chocked to see that initializing that took a few ms on phpQuery took almost 200ms for FluentDOM.

    $query = FluentDOM::QueryCss($html);

After a while I figured out that there was a large overhead when it tried to figure out what content it was given that I could get rid of by specifying that it was html I was feeding it with. So if I instead used

    $fd = FluentDOM::QueryCss($html, 'text/html');

the time for initialization was on par with phpQuery.

So I started updating some old code that used phpQuery and everything went smoothly. But a few times I ran into a minor issue where it would complain about tag mismatching etc. I was confused since html, contrary to xml, is very loose with this stuff. But then I noticed that when working with the supplied html, internally it was handled as xml and causing these "errors" when for instance doing append operations etc.

One part of me like that it complains so I can spot any issue and fix it. But another part of me feels its a bit confusing to be able to specify html but yet have it tested against the xml rules.

Is this by design, by mistake, by bug or just a side affect of libxml and other underlying libraries used?

**Comment by ThomasWeinert** [comment]
One part is by design. FluentDOMs default format is 'text/xml'. You just get a lot more XML in PHP. In the current stable version you can load HTML, but it expects XML fragments for the methods like `append()`. This is changed in the current development version. 

It now depends on the content type.
https://github.com/FluentDOM/FluentDOM/issues/39

The loaders are independent from the manipulation methods. It is a plugin interface and here are a lot more formats that you can load.

**Comment by inquam** [comment]
Yea, that was my guess. To have fragments be treated as the content type set feels like the correct way to go.

**Comment by ThomasWeinert** [comment]
I already created a branch that includes it. But the new issue #43 is related and changes the plugin api and the content type handling. So I would like to include that into the release.

You can change the require to `"fluentdom/fluentdom": "^6.0@dev"` to test the new version.

*btw* Here are two possible performance improvements depending on you usecase:

1. Use Xpath expression. (You can convert CSS to Xpath using http://xpath.thomas.weinert.info/)

If you use CSS selectors, the library needs to parse and transform them at runtime. However depending on the knowledge of your team, the Xpath expression might be less readable.

2. Use FluentDOM::load() (returns FluentDOM\Document, a DOMDocument child class)

FluentDOM\Query works with an array of nodes and has some internal sorting and normalization. FluentDOM\Document extends the DOM but it works directly on the DOM nodes.
