### ISSUE TITLE
Initialising FluentDOM query changes the underlying html

### ISSUE THREAD

**Issue by inquam** [FluentDOM/FluentDOM#42]
If I compare the output of

```
   $fd = FluentDOM::QueryCss($output, 'text/html');
   die($fd);
```

and

`die($output);`

I notice that the the output differs. Now, I have not done a single selection or change, only loaded the html and echoed it. What it seems to do is try to close tags but the problem is that it does so incorrectly.
In the middle of a bit of javascript it breaks the document.

This is what the original looks like if I don't run it through FluentDOM at all

```
   ...

   }).on('error', function (event, id, name, errorReason, xhrOrXdr) {
                            $('#restricted-fine-uploader .flashmessage-error').remove();
                            $('#restricted-fine-uploader').append('<div class="flashmessage flashmessage-error">' + errorReason + '<a class="close" onclick="javascript:$(\'.flashmessage-error\').remove();" >X</a></div>');

   ...
```

But if it is loaded into FluentDOM and echoed right away this changes to this

```
   ...

   }).on('error', function (event, id, name, errorReason, xhrOrXdr) {
                            $('#restricted-fine-uploader .flashmessage-error').remove();
                            $('#restricted-fine-uploader').append('<div class="flashmessage flashmessage-error">' + errorReason + '<a class="close" onclick="javascript:$(\'.flashmessage-error\').remove();" >X</script>
</fieldset>
</form>
</div>');

   ...
```

The closing of the **a** tag is removed and a closing **script** tag is instead inserted and several other tags to. My gut feeling makes me think it has something to do with issues handling scripts and text strings within scripts that contain html.

**Comment by ThomasWeinert** [comment]
That is not specific to FluentDOM. FluentDOM load the HTML into a DOMDocument using DOMDocument::loadHtml(). It uses PHPs DOM implementation, that is based on LibXML. The method will parse and "repair" the HTML.

I am not sure why the JS breaks the LibXML parser, it think the HTML is not valid.

HTMLTidy might be able to repair it in a way that keeps the structure.

**Comment by inquam** [comment]
I actually did test HTMLTidy and it fixed some of these issues. But it also contained behavior that I could not configure it not to do, such as removing empty tags etc. Since the provided document does contain that (and some of them are later filled via JS) this was impossible to use. HTMTidy also seems to not have been worked on for some time. A "new" version exists that seems to be HTML5 compatible and add a lot of new features and configuration options, but it's not the version shipped with PHP. Requiring people to manually build that and recompile PHP with the correct HTMLTidy files is a dependency I would like to avoid.

**Comment by ThomasWeinert** [comment]
Here is a [HTML 5 loader/serializer](https://github.com/FluentDOM/HTML5) for FluentDOM as well. The library converts the HTML5 into XHTML for the DOM. Maybe this can help. If you can find another library it would be possible to add a loader/serializer as well.
