### ISSUE TITLE
Implicit namespaces in html?

### ISSUE THREAD

**Issue by amnuts** [FluentDOM/FluentDOM#47]
Is there any way to have custom tags with implicit name spaces left alone?  For example, I have a custom tags along the lines of:

```
<wt:folder id="123" foo="bar">blah blah</wt:folder>
<wt:person id="1234" />
```

I use some parsers to convert certain blocks of html to other html structures, each parser processes the html and then ends up returning the finished html with:

```
$fd = \FluentDOM::load($html, 'text/html');
$fd->registerNamespace('wt', 'urn:wt');
// do some stuff here with the nodes
return new \FluentDOM\HTML5\Serializer($return->document);
```

Eventually, when all the parsers are finished, I have to seemingly load it back into FluentDOM to be able to get just the content of the body tag (unless there's a way to output the content without the body wrappers and doctype, etc.?):

```
$fd = \FluentDOM($html, 'text/html');
$fd->registerNamespace('wt', 'urn:wt');
return $fd->find('body')->html();
```

But it will output the custom tag as something like:

```
<folder foo="bar" something="other" xmlns:wt="">blah blah</folder>
```

Is there any way to retain the original format of the tag?

**Comment by ThomasWeinert** [comment]
That will not work in HTML, only XML (XHTML). HTML does not have namespaces, so libxml removes them. HTML5 only has specific namespaces with several reserved prefixes (svg, ...). You will have to use XML.

Additionally `*->registerNamespace()` in FluentDOM only registers the namespaces for the API. It will not affect the document - only your method/function calls.
