### ISSUE TITLE
Getting the  element's tag name

### ISSUE THREAD

**Issue by xfactor5** [FluentDOM/FluentDOM#48]
Hi,
I pass nodes to different classes for special handling, I want each class to check if the correct tag type has been provided. I can check if required attributes are there with hasAttr but how do I check if the correct tag is provided in the query?
I think it is possible to get tag name by using the dom object associated with the node but that would somehow kill the purpose. How about adding a function for this?
Thanks

**Comment by ThomasWeinert** [comment]
Not really, `FluentDOM\Query` is a node list, just like jQuery. If you're working with a single node, using the extended DOM node objects is not a bad idea. If you iterate a `FluentDOM\Query` the items are node objects. `FluentDOM\Element` even provides `ArrayAccess` for the attributes.

See: https://github.com/FluentDOM/FluentDOM/wiki/Element-ArrayAccess

A node name is complex. It is actually 3 properties. `DOMNode::$nodeName`,  `DOMNode::$localName` and `DOMNode::$namespaceURI`.  The node name is the tag name including the namespace prefix. It is not stable (the namespace prefix can change and is optional). To validate a node you should verify the local name and the namespace URI.

```php
if ($node->namespaceURI= 'urn:foo' && $node->localName = 'foo') {
  ...
}
```

So I suggesting working with the element nodes and only putting them back into a FluentDOM\Query if you really need the traversing/manipulation API again.

Additionally `FluentDOM\Query::is()` and `FluentDOM\Query::filter()` could be used to verify the condition.

**Comment by xfactor5** [comment]
Thanks Thomas, but I still believe adding functions for getting full name or local name to your query/element object would be very useful. Something like this:

`$fd->find('//div')->children()->first()->getlocalTagName()`

+ Most XML documents used in the web for casual porpuses don't have namespaces. Including, HTML.

**Comment by ThomasWeinert** [comment]
Why not just:

`$fd->find('//div')->children()[0]->localName`

or as a validation

`$fd->find('//div')->children()->first()->is('local-name() = "span"')`

The jQuery API is large and a little messy. So I am feeling a little queasy about adding more methods. Especially if they are not in jQuery.

**Comment by xfactor5** [comment]
I understand your feeling ... but ... you know ... people care about methods that are not there, not the extra methods that they do not use. It's also quite a useful feature. And "children()[0]->localName" is not as elegant as "getLocalName()".
Anyway, it's your library and you're in charge. Do what you believe is the best...

**Comment by ThomasWeinert** [comment]
Well it is `FluentDOM($node)[0]->localName` vs `FluentDOM($node)->getLocalName()`. The difference is not that big.
