### ISSUE TITLE
Loading from a DOMNode

### ISSUE THREAD

**Issue by xfactor5** [FluentDOM/FluentDOM#49]
Hi,
I have a complex system that performs different handling types on a dom document using PHP's DOMDocument, for one part I have chosen FluentDOM to handle only a special part of the document (a large element). Is it possible to load FluentDom with a DOMNode object?
Right now, we can only load a whole document but, for performance issues, I don't want to reload it again . It would be great if I could pass that special DOMNode to FluentDom.

Something like this is what we do in jquery, where "element" can be a jquery object or a DOM object:
`$(element).text('foo bar');`

**Comment by ThomasWeinert** [comment]
It work exactly the same in FluentDOM.

`FluentDOM($element)->text('foo bar');`

**Comment by xfactor5** [comment]
Thanks for the clarification. Was it in the docs? I couldn't find it there.

**Comment by ThomasWeinert** [comment]
https://github.com/FluentDOM/FluentDOM/wiki/Nodes-Load
