### ISSUE TITLE
Package suggests fluentdom/css-selector

### ISSUE THREAD

**Issue by kelunik** [FluentDOM/FluentDOM#51]
Package suggests `fluentdom/css-selector`, but it should be `fluentdom/selectors-phpcss`.

**Comment by ThomasWeinert** [comment]
No, bot `fluentdom/selectors-phpcss`  and `FluentDOM/Selectors-Symfony
` provide `fluentdom/css-selector`. It's a a virtual package:

**Comment by kelunik** [comment]
Ah, fine, thanks!
