### ISSUE TITLE
How to install ext in Windows

### ISSUE THREAD

**Issue by InVinCiblezz** [FluentDOM/FluentDOM#68]
```
$ php 01_read-html.php
PHP Warning:  failed loading cafile stream: `D:/coding/language/php7/extras/cetr
/cacert.pem' in E:\FluentDOM\src\FluentDOM\Loader\Html.php on line 57
```
i saw some answers about 'apt..', but i' m in windows with php7

**Comment by ThomasWeinert** [comment]
This is not really something that has to do with FluentDOM. I imagine that you're loading an URL, maybe HTTPS. Try to load it separatly:

`$string = file_get_contents('https://...');`

This should result in the same or a more specific error message. 

Here is more about the problem: http://stackoverflow.com/questions/2305954/how-to-enable-https-stream-wrappers
